PUT  http://localhost:3000/user/reg/
content-type: application/json

{
    "mail": "delete3@gmail.com", "pass": "password", "age": 130
}

###

POST  http://localhost:3000/user/login/
content-type: application/json

{
    "mail": "changed@gmail.com", "pass": "newpassword"
}

###


PUT  http://localhost:3000/user/update/
content-type: application/json

{
    "mail": "example1@gmail.com", "pass": "password", "new-mail": "changed@gmail.com", "new-pass": "newpassword"
}

###

DELETE http://localhost:3000/user/delete/
Content-Type: application/json

{
    "mail": "delete2@gmail.com", "pass": "password"
}

###
GET http://localhost:3000/user/get/
Content-Type: application/json

###

GET http://localhost:3000/scrape/scrape/
Content-Type: application/json